# Generated by Django 2.1.7 on 2019-12-11 11:07

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Chained', '0005_auto_20191211_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Chained.City'),
        ),
    ]
